src/app/app.module.ts, src/app/blocks/audio-player-block/audio-player-block.component.html, src/app/blocks/web-money/web-money.component.html, src/app/blocks/web-money/web-money.component.ts, src/app/components/blocks-workflow/blocks-workflow.component.html
Adds a new 'web-money' block, and makes player pause and play "sub-block" events work properly.
It can be used like this:
```javascript:
{
"title": "Basic Player Web Money",
"blocks": [
{
"type": "init"
},
{
"type": "mapping",
"mapping": "\n    {\n  \"display_artist\": 'Artist name',\n  \"display_title\": 'Track title',\n  \"url\": 'track.mp3',\n  \"paymentPointer\":'$ilp.example.com/some_payment_pointer}\n"
},
{
"type": "player",
"titleMapping": "data && data.join(' - ', [display_artist, display_title])",
"onPlay": [
{
"type": "web-money"
}
],
"onPause": [
{
"type": "web-money",
"enabled": false
}
]
}
],
"id": "basicPlayerWebMoney",
"adapterName": "examples"
}
```
Part of https://linear.app/kendraio/issue/K-54/demo-playing-a-track-and-tipping
=> New web-money block for K-54

src/app/blocks/web-money/web-money.component.html, src/app/blocks/web-money/web-money.component.ts
Detects Web Monetization support and allows custom messaging for:
- support found
- support missing
- active payment
- paused payment
I added some default messaging.
I made it so the payment pointer visibility could be configured.
Default no support messaging:
Default success (demo gif):
https://linear.app/kendraio/issue/K-60/show-custom-messages-based-on-web-monetization-support
=> K-60: 'Web money' support text

src/app/blocks/web-money/web-money.component.html, src/app/blocks/web-money/web-money.component.ts, src/app/components/waveform/waveform.component.html
Adds header text "Payment pointer:" 
web-money block can now use the 'paymentActiveMessage' config.
Removes misleading "Now playing" text from Waveform (that would have displayed even when actually paused)
=> Player UI updates (K-98 / #167)

docs/workflow/blocks/player.rst, docs/workflow/blocks/web_money.rst, src/app/blocks/web-money/web-money.component.html, src/app/blocks/web-money/web-money.component.ts
Reveals the payment stream amounts to the end user, as a total of the native [crypto] currency amount for the current session, and estimates the value transferred in a fiat currency, to help the user understand the value exchange.
Adds a new 'fiatCurrency' configuration property that defaults to 'usd', but accepts 'eur', 'gbp' etc.
CoinGeck is used to estimate the amount with live market exchange rate data per session. 
They provide free access, and work without API keys, or server side code, across origins and I found a way to do it with a single request to avoid excess loading time of request chaining.
I've noticed only XRP in the native currency format so far when testing with Coil. 
I've also added basic documentation for the Web Money block and Player block.
=> Show latest payment stream amount  (K-101 / #170), documentation

package-lock.json, package.json, src/app/blocks/web-money/tracking.ts, src/app/blocks/web-money/web-money.component.ts
A fairly generic tracking module is added that sends a Graphql instance data no more than once every 10 seconds.
It is used by Web Money when tracking is enabled via block config.
It may be tested by viewing the "player/all" flow.
=> K-108 / #175 - Tracking play statistics

src/app/components/blocks-editor/blocks-editor.component.html, src/app/components/blocks-editor/blocks-editor.component.scss, src/app/components/blocks-editor/blocks-editor.component.ts, src/app/dialogs/add-block-dialog/add-block-dialog.component.html, src/app/dialogs/add-block-dialog/add-block-dialog.component.scss
Adds icons to the list of blocks in the workflow sidebar.
When adding a block task, you can now see text in the block modal without having to mouseover.
=> Icons and text of blocks

firebase.json
We still want to allow images from anywhere, and any connect-src cross domain requests but most other things are locked down.
=> Limit CSP wildcards to connect and images

firebase.json
A stylesheet aimed to set it's media type to all useragent types, rather than being print specific by doing this inline script after it loaded:
"this.media='all'"
It failed due to the Content-Security-Policy, but by hashing the inline script, and adding it to the allow list, I hope to remedy the issue and fix the CSS.
=> Whitelist Angular onload style change script

angular.json
Though the CSP issue seems resolved in Chrome and Firefox, Safari/WebKit says:`Refused to execute a script for an inline event handler because 'unsafe-inline' does not appear in the script-src ` and refuses to show the page correctly unless inline optimizations are turned off.
So this turns them off.
=> Angular CSP fix: disabling inline optimizations

.gitignore, angular.json
This is the fix to enable the CLI to work again. It also re-enables the automatic creation of testing files. 
To test this change you can use these commands: 
` ng generate service services/test-service `
and 
`ng generate component blocks/test-block`
Both these should work, creating framework files. In the case of the component, a template .scss file should be created, not a .css file. 
Fixes #239
=> Removing incompatible changes from angular.json

cypress.json, cypress/integration/context_and_state.ts, cypress/integration/spec.ts, src/app/blocks/mapping-block/mapping-util.spec.ts
This PR fixes observed Cypress CI failures by:
- increasing the page load timeout, 
- increases the default Cypress command timeouts.
- disabling videos.
=> CI reliability fixes: expands timeouts duration, disables unused video capture #246

src/app/blocks/grid-block/grid-block.component.ts
When the grid is disabled, it disappears from the DOM. Sometimes there is an event waiting, and this can no longer find the grid, and throws an error.
=> Grid EnabledGetter - Error: Cannot read properties of undefined

cypress/integration/templates_and_export.ts, docs/workflow/blocks/template.rst, src/app/blocks/template-block/template-block.component.ts
This is a small update to the template block that will places the rendered html from a template block into the data model. This makes it possible to build flows that can export HTML.
=> Update template block to allow rendered html to be accessible in a flow

cypress/integration/authentication.ts, src/app/services/auth.service.ts
This update provides a simple additional behaviour for the auth0 callback page. If no authentication data is passed in the url, then the user is forwarded directly to the user page. A user should never be left on this page, and since this is an authentication callback, we can safely send users to the /user page. 
The Auth0 login process for Youtube seems to cause the callback page to be reloaded after authentication is complete. The second call is missing the authentication payload, and without any default action, we get stuck. 
I would like to find the source of the second redirect, but it has so far taken enough time, and may not be worth further investment.
=> Auth0 Callback page now has default behaviour

docs/index.rst, docs/workflow/blocks/context_block.rst, docs/workflow/blocks/context_runner_block.rst, src/app/blocks/context-block/context-block.component.ts
Comments the code in JSDoc style, adds new documentation as below, and adds links between the docs for the two context blocks.
Context Runner Block
====================
The Context block is a good way to run more complicated flows that depend on a value from an asynchronous source, like an API call or user input.
The Context block accepts a list of blocks, contextBlocks, a contextPath and a list of blocks, blocks.
The Context block is configured with two flows. The first flow, contextBlocks, is run first. Once the contextBlocks flow yields a result, the Context block runs the blocks flow, and blocks can load the value from the contextPath using a block like the Mapping block.
In the below example, Dropbox uploads are listed. The contextBlocks sub-flow gets a token from a auth0 block, and …
=> Context documentation

cypress/e2e/http_block_page_following.ts, docs/workflow/blocks/http.rst, src/app/blocks/http-block/http-block.component.spec.ts, src/app/blocks/http-block/http-block.component.ts
When HTTP block config declares followPaginationLinksMerged as true, the block will try to follow linked pages and combine the results into a single combined array.
After getting a page, if the `link` response header links to a next page, it requests it (until there are no more) then it merges results to return a single output.
You can see it in use here, where instead of the usual 1 request with up to 100 results, there are hundreds of results and quite a few HTTP requests made:
https://kendraio-app-git-paginated-http-block-kendraio.vercel.app/mygreenpod/cart
=>  HTTP block pagination support

src/styles.scss, src/styles/vendor.scss
You should be able to go to:
https://kendraio-app-git-angular-material-theme-import-7b70b9-kendraio.vercel.app/localloop/filterTransactionsByOrg
and see that the dropdown  has a background and in general things are formatted better than main's prod deployment:
https://app.kendra.io/localloop/filterTransactionsByOrg
=> Angular material theme import fix (GH issue #370)

docs/workflow/blocks/mapping.rst
Add ISO 8601 example for formatDate() in JMESPath Mapping documentation
=> Add ISO 8601 example to Mapping docs

docs/workflow/blocks/form.rst, docs/workflow/blocks/mapping.rst, docs/workflow/blocks/variable_set.rst
Some small but helpful improvements in Kendraio Docs about Form block
Linear ticket [K-332](https://linear.app/kendraio/issue/K-332/update-form-documentation)
=> Update documentation - Form Block

.gitignore, docs/documentation.rst, docs/extract-example-block-usage-from-flows.js, docs/flow-analysis/README.md
We often need to look at examples of Flows using specific blocks, and sometimes specific config properties on them - like Forms using "uiSchema". I (well, and GPT-4) made this to help make that process much faster.
=> Adds a script to find examples of particular blocks using specific properties from Flow Cloud

cypress/e2e/http_block.ts, docs/workflow/blocks/http.rst, src/app/blocks/http-block/http-block.component.ts
Currently, the HTTP block handle error in the code but it does not return any information about it.
If a GET/POST/PUT/... request is made and an error is raised, the data object in the flow is `null`
With this PR the data object in the flow, will now return the error information.
It also contain a very handy `hasError: true` property so it can be easily check for error or not and potentially display error messages in the flow.
Here two screenshots of how the result will be:
And here is a flow that can be use to test this PR: [Kendraio Harvest Time](https://app.kendra.io/harvest-timesheet/harvestTimesheet)
Linear Issue [K-361](https://linear.app/kendraio/issue/K-361/kendraio-time-flow)
=> Return error information on HTTP block request

docs/workflow/blocks/mapping.rst, src/app/blocks/mapping-block/mapping-util.spec.ts, src/app/blocks/mapping-block/mapping-util.ts
This update extends JMESPath functionality to include replaceAll and toUpper functions, along with tests.
The docs have also been updated with usage instructions for the new functions. There is some minor rephrasing of related functions in the interest of linguistic consistency.
=> Adds toUppercase and replaceAll functions

cypress.config.ts
This code change introduces a Run All Specs button to the Electron Browser by adding the setting to cypress.config.ts. This makes our end to end tests much easier to run.
=> Add Run All Specs button to Electron browser

.github/ISSUE_TEMPLATE/bug_report.md
Adds a template to help ensure we capture key details so we can reproduce them, know how important problems are, and so on.
=> Add GitHub Issue template

cypress/e2e/gosub.ts, cypress/e2e/share.ts, cypress/e2e/spec.ts, src/app/app.component.html, src/app/components/blocks-editor/blocks-editor.component.html, src/app/components/workflow-sidenav/workflow-sidenav.component.html, src/app/dialogs/add-block-dialog/add-block-dialog.component.html, src/app/dialogs/show-share-link-dialog/show-share-link-dialog.component.html
This PR take care of the task: `Review tests, are force clicks needed with new Cypress version?` from[ Angular 16 Issue](https://github.com/kendraio/kendraio-app/issues/440)
`force:click` is [a functionality of Cypress ](https://docs.cypress.io/api/commands/click#Options) and is present in all the versions. 
It is used when an element needs to be clicked, but it is hidden by another element. (For example, a menu that shows up when user over on another element)
As per [documentation](https://docs.cypress.io/guides/references/error-messages#Ignore-built-in-error-checking) and best practice, we should not overuse it: 
> Be careful with this option. It's possible to force your tests to pass when the element is actually not interactable in your application.
To avoid using it, there is no …
=> Cypress: Remove force:true from click 

docs/workflow/blocks/mapping.rst
See https://github.com/kendraio/kendraio-app/issues/465 for more info.
=> Documentation fix: Mapping Block `now` function uses RFC 7231 not ISO 8601

src/app/blocks/web-money/web-money.component.ts
Uses a timer to emulate Web Monetization events since Coil have stopped their service.
It's for use by the Web Money block, along side the Player block for sending music statistics to "DSP-1" / "Distributor".
Please note that https://kendraio-app-git-player-statistics-kendraio.vercel.app/player/all does not play because of a CORS issue but will when ran via localhost. When ran there will be network events when audio is playing.
Testing example:
1. You can locally build, and run the server.
2. Look at existing state of the stats here: http://localhost:4200/dsp1/myStats
3. In a new tab, play a track from: http://localhost:4200/player/all
4. In another tab, a few seconds later, you can load http://localhost:4200/dsp1/myStats again and should see that the statistics page has updated.
=> Coil Web Monetization event simulation feature

src/app/blocks/map-block/map-block.component.ts
Makes Map block able to accept a "country" property in the array of map points it processes, that show as an area, the values must be 3 letter ISO country codes.
Shading for area can be adjusted.
Custom map pin points may be set to an emoji flag.
Documentation has been removed from this branch.
A unit tests file for the block was added but is removed from this branch.
This should meet requirements for: https://github.com/kendraio/kendraio-app/issues/483
To help deliver the code changes faster for Donald to use from main, my existing pull request which code, tests and documentation are to be broken up, with these code changes to be pursued first. The rest need doing for this issue: https://github.com/kendraio/kendraio-app/issues/488
=> Map country areas and makes map points optional if country is used

.github/actions/tests/Dockerfile
**Fixes broken tests caused by old Cypress container**
Our GitHub Actions tests started failing because the Cypress Docker image was based on Debian Buster, which has reached end-of-life, and the package repositories are no longer readily accessible.
The container runs our unit tests and the end-to-end Cypress tests.
This upgrades the container from `cypress/included:8.4.1` to `cypress/included:14.5.1`, which uses a supported Debian version and already includes Node.js v22.17.
**Changes:**
- Upgrades Cypress container to 14.5.1
- Removed redundant Node.js 18 installation (now included)
- Added `xauth` package (required but no longer bundled)
Fixes #544
=> Upgrades Cypress container to 14.5.1
