.nowignore
angular.json
now.json
package.json
yarn.lock

Test now deployment for test branches

adding now config

---

src/app/blocks/web-money/web-money.component.html
src/app/blocks/web-money/web-money.component.ts

Implements the frontend part of https://github.com/kendraio/kendraio-app/issues/159

K-70 Coil login button

---

README.md
src/app/blocks/web-money/web-money.component.html
src/app/blocks/web-money/web-money.component.ts
src/app/dialogs/add-block-dialog/block-types.ts

- This fix ensures the latest app URL is used for the redirect back from Coil. (K-91, #163)
- The player description no longer describes the Web Monetization support as "in development". (K-90)
-  "No Web Monetization extension found 😟." is no longer shown since we have a solution with Coil login. (K-89)
-  Adds developer setup documentation to README (from Google Doc)

Generates login URL (with redirect) after config event, copy fixes and readme improvement 

---

firebase.json

Tested locally with https://chrome.google.com/webstore/detail/csp-tester/ehmipebdmhlmikaopdfoinmcjhhfadlf

Adds CSP restrictions, allows Angular to eval select sources

---

firebase.json

Mirroring the X-Frame-Options header with CSP header rule.

CSP rule to deny embedding site in a frame

---

docs/conf.py
docs/index.rst
docs/workflow/blocks/wallet.rst
docs/workflow/blocks/web_money.rst
package-lock.json
package.json
src/app/_shared/services/uphold_service.ts
src/app/app.module.ts
src/app/blocks/wallet/wallet.component.html
src/app/blocks/wallet/wallet.component.ts
src/app/components/blocks-editor/blocks-editor.component.html
src/app/components/blocks-editor/blocks-editor.component.ts
src/app/components/blocks-workflow/blocks-workflow.component.html
src/app/dialogs/add-block-dialog/block-types.ts
src/environments/environment.dev.ts
src/environments/environment.prod.ts
src/environments/environment.ts

New Wallet block with previously demoed functionality.
Also recently since I merged servers for oauth and CORS proxying,  the structure of the requests changed, and real prod endpoints now exists, and some other small changes.
Also uses Block names in app UI.
Hopefully this is ready for prod time!

Wallet block

---

src/app/_shared/services/uphold_service.ts
src/app/blocks/wallet/wallet.component.ts

Checks we have auth token before trying request.
Raises an error if service is used without key.
To prevent this:

#209 Wallet block now wait for key before making requests

---

angular.json
cypress/fixtures/dummyWorkflow1.json
cypress/integration/context_and_state.ts
cypress/integration/spec.ts
src/app/app-routing.module.ts
src/app/auth/dirty.guard.spec.ts
src/app/auth/dirty.guard.ts
src/app/components/not-found/not-found.component.ts
src/app/services/dirty-dialog.service.spec.ts
src/app/services/dirty-dialog.service.ts
src/app/services/workflow.service.ts

This is an implementation of a popup message to warn a user that some changes to the workflow have not been saved.

Deactivate guard

---

cypress/fixtures/develModeBlocks.json
cypress/fixtures/stateAwareBlocks.json
cypress/integration/context_and_state.ts
src/app/blocks/file-input-block/file-input-block.component.html
src/app/blocks/file-input-block/file-input-block.component.ts

This PR updates the file input block to be state aware, and adds "EnabledGetter" functionality to allow the button to be revealed or hidden based on state.

File input extended to support state

---

cypress/fixtures/stateAwareBlocks.json
cypress/integration/context_and_state.ts
src/app/blocks/file-input-block/file-input-block.component.html
src/app/blocks/file-input-block/file-input-block.component.ts
src/app/blocks/grid-block/grid-block.component.ts

This small release contains a minor bug fix to prevent a pop-up error message, and an updated, state-enabled file-import block.

Updates for file importer

---

functions/package-lock.json
package-lock.json
package.json

This is a testing branch for integrating the security updates from dependabot.

286 dependabot updates

---

.github/workflows/main.yml

Allow us to deploy to firebase.

--legacy-peer-deps

---

.devcontainer/devcontainer.json
README.md
angular.json

This is an initial setup to get codespaces working. 
Minimal devcontainer definition and readme file updates.

Codespaces config

---

docs/workflow/blocks/load_schema.rst
src/app/blocks/load-schema-block/load-schema-block.component.ts
src/app/blocks/load-schema-block/load-schema-block.spec.ts

- Documents  load-schema block functionality better 
- Adds some Angular tests for key new load-schema block functionality.

Load schema tests and documentation

---

docs/workflow/blocks/mapping.rst
src/app/blocks/mapping-block/mapping-util.spec.ts
src/app/blocks/mapping-block/mapping-util.ts

In addition to second input, the new method now accepts millisecond format, and expects to be told the format.

Parse unix timestamp millisecond input GH-371

---

src/environments/environment.dev.ts
src/environments/environment.prod.ts
src/environments/environment.ts

This will help get Google and YouTube OAuth flows using Auth0 working again.

Switches Auth0 proxy hostname to Vercel not now.sh

---

docs/workflow/blocks/form.rst
docs/workflow/blocks/mapping.rst
docs/workflow/blocks/variable_set.rst
src/environments/environment.dev.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/styles/main.scss

We need to get the real app working to fix YouTube.

Merge develop with YouTube fix and others

---

docs/workflow/blocks/batch.rst
src/app/blocks/batch-block/batch-block.component.scss
src/app/blocks/batch-block/batch-block.component.ts
src/styles.scss
src/styles/main.scss

Improve flexbox batch block

---

src/app/blocks/card-block/card-block.component.scss
src/styles/main.scss

- remove padding around image
- make image take all the container's space
- move card style in card style's component
- add truncate helper class and documentation in style.scss

Fix card's style

---

docs/conf.py

Fixes docs copyright year, author, owner

---

LICENSE

Fixes license year and adds Kendraio Foundation MTÜ

---

docs/index.rst
docs/requirements.txt
docs/workflow/blocks/launch_block.rst
docs/workflow/blocks/mapping.rst

In the past months we have improved and fix our documentation but we forget to build it so the edit are not visible in production.
In this PR I:
- built the documentation 
- I added some required packages to the python package manager  
- I fix some page of the doc that did not look good. 
To see if it works you can run the documentation on your local with the command `sphinx-autobuild docs/ docs/_build/html`
and then access the documentation at `http://127.0.0.1:8000`
If you get some error, please refer to the doc to see if you have installed all the required libraries to run the doc:  https://kendraio-app.readthedocs.io/en/latest/documentation.html

Build the update version of the documentation

---

README.md

It doesn't work and we don't want it.

Remove Uptime badge from README.md
